language: node_js
node_js:
- node
after_success: npm run coverage
env:
  global:
    secure: cF+Jk6PmX61bWoF+CjzIchzO87ZcfgUCL0/JMwmA7ysK2TAu07KGOr34tkRjMFC+0YitbRhykXSdGLsAMWwOf6ghX1VzyA7YcKvGay2mcd0lzsEY9/M9mwTHXDbWytJyxxQYrcRmU3LiG6RFjNuIy4albrAlhq9PvWUPzxfs2dlAbi2kHbkz/a+dcErzMk5gc+X+KS85MYP3BHAqbbkGA5NOZx6U3O3gIPJZD+wGKlUGgquO1CYV43t+rGpxrCbUuDkb9LoPK8pvep4jjLqcqQ39/TskiJ/VmIoNeWlnZgwiPAB0ySB0wboWRUGf82XYVRB6pz7vzsKqBpNw0Ecb6+BWP2B662zc8qPirff3+Vb/bKRf5NHKvAEkA0twTkxOci00ABBzvLZKu/KUE189mliiq2TB/ghXnR9SbxUOVyMANgczLfYhHVCJbGTOZyl5li5C2Uh2kEr4GTt9m8ywkYf0wqEOv+TEgFbicnqRy8if5o1w+VEuutblO70ZfeFR7LrQcBPQdbz9OBrJuqTt/ReGcMZV/QWL+yxGJO5cbnH6Ghhq5zrykInvp+XkqaZcw1ALt33MbqUSbvNys2K7DEK7M/CRxQdRra5thgSLHBW+NDagshvX9O/ZRq9HQ8heMkOM4A5kyKhL1yz4mylyVTGqYo45Q2DmDfG99FmDWPQ=
